X_INCDIRS	+= Tinyhttpd-WebDAV
X_LIBS		+= libxlibc.a libnetc.a
X_CFLAGS	+= -D__NXOS__

NAME		:= webdav.xapp
SRC			+= httpd.c

define CUSTOM_TARGET_CMD
echo [APP] $@; \
$(LD) $(X_LDFLAGS) $(X_OBJS) -o $@ $(patsubst %, -L%, $(X_LIBDIRS)) \
	--start-group $(patsubst %, -l:%, $(X_LIBS)) --end-group
endef
